### PR TITLE
Support laravel 8

### PR DESCRIPTION
**Pull request by miraries**
Not sure if you want to make old laravel versions incompatible since no changes in the actual package were made but I see that was done for the previous version so:
- Updated dependencies
- Updated factories
- Removed unsupported php from travis
- Migrated phpunit configuration
- Updated readme to reflect that [phpredis is now default in laravel](https://laravel.com/docs/8.x/redis#configuration)

### CODE REVIEW

**Comment by spiritix** [comment]
Hi @miraries. Sorry for the late reply, missed this PR somehow. The question is - does the updated version still work with Laravel 7? If so, there is no need in making it incompatible.

**Comment by miraries** [comment]
Hey! That's ok. From what I could gather it should still work with Laravel 7. The breaking changes are only in the tests due to factories. Also I haven't run into any issues running it on Laravel 8 since making this PR.

I will update the dependencies and check later just in case.

**Comment by spiritix** [comment]
Then we should set the minimum dependencies to Laravel 7, but keep them on Laravel 8 for development environment. Like this the tests will pass and we don't make L7 incompatible.

**Comment by abishekrsrikaanth** [comment]
if we update the composer dependencies to support L7 and L8, wont we be good with the upgrade? Currently the composer dependencies only allow L7 support

**Comment by abishekrsrikaanth** [comment]
```
    "require": {
        "php": ">=7.2|7.3",
        "illuminate/support": "^7.0|^8.0",
        "illuminate/database": "^7.0|^8.0",
        "illuminate/redis": "^7.0|^8.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^8.0|^9.0",
        "orchestra/testbench": "^5.1|^6.0",
        "mockery/mockery": "^1.3",
        "barryvdh/laravel-debugbar": "^3.2"
    },
```

**Comment by miraries** [comment]
Updated the dependencies and the readme, check when you can @spiritix

**Comment by spiritix** [comment]
Thanks a lot, guys. Will publish a new release as soon as I've tested everything.

**Pull request merged**
